project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "US Baby Names"
  author:
    - Alyssa W. Zhang (awz2109)
  repo-url: https://github.com/alyssawzhang/babynames
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


